# Generated by Django 3.0.4 on 2020-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200402_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_about', models.CharField(max_length=50, verbose_name='Hakkınızda')),
                ('user_phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('user_prof', models.CharField(max_length=50, verbose_name='Uzmanlık Alanı')),
                ('user_links', models.CharField(max_length=50, verbose_name='Websiteler')),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekle')),
            ],
        ),
    ]
