# Generated by Django 3.0.4 on 2020-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='user_about',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='user_links',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='user_prof',
        ),
    ]
